apiVersion: v1
kind: Template
metadata:
  name: cloud-native-frontend-template
annotations:
    description: "A SpringBoot microservice which communicates with backend and provides a UI to operate on notes"
# Parameters
parameters:
- name: ARTIFACT_COPY_ARGS
  description: Syntax to be used to copy uberjar files to the target directory
  displayName: Copy Args
  value: '*-exec.jar'
  required: true
# Objects defined for the template
objects:
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: cloud-native-front
      group: me.snowdrop
      version: 1.0-SNAPSHOT
    name: cloud-native-front
  spec:
    ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: cloud-native-front
      group: me.snowdrop
- apiVersion: v1
  kind: Route
  metadata:
    labels:
      app: cloud-native-front
      group: me.snowdrop
      version: 1.0-SNAPSHOT
    name: cloud-native-front
  spec:
    port:
      targetPort: 8080
    to:
      kind: Service
      name: cloud-native-front
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: cloud-native-front
      group: me.snowdrop
      version: 1.0-SNAPSHOT
    name: cloud-native-front
  spec:
    replicas: 1
    selector:
      app: cloud-native-front
      group: me.snowdrop
      version: 1.0-SNAPSHOT
    strategy:
      rollingParams:
        timeoutSeconds: 3600
      type: Rolling
    template:
      metadata:
        labels:
          app: cloud-native-front
          group: me.snowdrop
          version: 1.0-SNAPSHOT
      spec:
        containers:
        - env:
          - name: KUBERNETES_NAMESPACE
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
          - name: OPENTRACING_JAEGER_HTTP_SENDER_URL
            value: http://jaeger-collector.tracing.svc:14268/api/traces
          - name: OPENTRACING_JAEGER_SERVICE_NAME
            value: cloud-native-frontend
          image: cloud-native-front:latest
          imagePullPolicy: IfNotPresent
          name: spring-boot
          ports:
          - containerPort: 8080
            name: http
            protocol: TCP
          - containerPort: 8778
            name: jolokia
            protocol: TCP
          securityContext:
            privileged: false
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - spring-boot
        from:
          kind: ImageStreamTag
          name: cloud-native-front:latest
      type: ImageChange
- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: cloud-native-front-s2i
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: cloud-native-front:latest
    postCommit: {}
    resources: {}
    source:
      binary: {}
      type: Binary
    strategy:
      sourceStrategy:
        env:
        - name: ARTIFACT_COPY_ARGS
          value: ${ARTIFACT_COPY_ARGS}
        from:
          kind: ImageStreamTag
          name: frontend-runtime:latest
      type: Source
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: cloud-native-front
  spec: {}
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: frontend-runtime
  spec:
    tags:
    - name: latest
      from:
        kind: DockerImage
        name: registry.access.redhat.com/redhat-openjdk-18/openjdk18-openshift:1.2-6